### PR TITLE
Feat: cookie storage

### PR DESCRIPTION
**Pull request by juls0730**
Build off of #221 and make SSR better with cookie storage. The original PR seems a bit dead, and I want to get this past the finish line. I'm unsure if manniL or Hossein-Mirazimi forgot about the PR or something, but I'm trying to just get it merged lol

### CODE REVIEW

**Comment by juls0730** [comment]
still working on merge conflicts and other small problems, please hold

**Comment by juls0730** [comment]
that should have the SSR working, and it will look similar to the demo page (whether its supposed to looks broken I'm unsure, but I made it look like the demo page). Once again, I must thank manniL from the original pull request for all of their great work

**Comment by wkl007** [comment]
@juls0730  How is the progress of this pr now, thank you！

**Comment by juls0730** [comment]
Hey @wkl007 i believe it was working when I closed it, but I can check again and confirm

**Comment by juls0730** [comment]
update: there is absolutely no way it was working when I closed the PR because I'm pretty confident it was not adding the class server-side, it is now doing that on the latest commit

**Comment by wkl007** [comment]
@juls0730 Thank you very much for your reply.

**Pull request closed without merging**
