### PR TITLE
fix: trim minified script

### LINKED ISSUE #266: feat: link script in head for CSP 'self' compliance in v3
### Is your feature request related to a problem? Please describe.
I'd like to not have any inline scripts to enforce a strict Content Security Policy.

### Describe the solution you'd like
The color-mode `script` should not be inlined as done here https://github.com/nuxt-modules/color-mode/blob/65c90d46372867e1d28a3bbd4ee975c05932f41e/src/runtime/nitro-plugin.ts#L7 but instead be an external file that is linked.

### Describe alternatives you've considered
Set `script-src: 'unsafe-inline'` (which is unsafe)

### Additional context
This was previously done for Nuxt 2 here: https://github.com/nuxt-modules/color-mode/blob/65c90d46372867e1d28a3bbd4ee975c05932f41e/src/runtime/nitro-plugin.ts#L7

### PR DESCRIPTION
**Pull request by Gerbuuun**
Possibly resolves #266 #267 #228

see my comments in #266

### CODE REVIEW

**Comment by danielroe** [comment]
This seems likely a bug in Nuxt security module but I don’t see a harm in this hotfix.

**Review by danielroe — APPROVED** [review]

**Comment by Gerbuuun** [comment]
Would be better if this could be achieved in the minification build step itself.

I'll raise the issue with nuxt-security

**Comment by Gerbuuun** [comment]
They already had a fix ready (https://github.com/Baroshem/nuxt-security/pull/478).
You can dismiss this PR if you think it is not necessary

**Comment by danielroe** [comment]
This PR is good (though the underlying bug in the regexp in nuxt-security does need to be fixed as well.)

**Comment by Gerbuuun** [comment]
A new version of `nuxt-security` has been released with the previously linked PR. It works now!

**Pull request merged**
