### PR TITLE
fix: added support for IE 11

### PR DESCRIPTION
**Pull request by shtinmn**
- Added support for IE 11 ( don't forget to build script.min.js =) )

I'm not 100% sure that babel can be divided into test and production, pay attention to this. 

Thank's

### CODE REVIEW

**Comment by Atinux** [comment]
Hi @shtinmn 

Thanks for the PR! Do you mind fixing the conflicts please?

**Comment by shtinmn** [comment]
Hi, @Atinux 

I'm fixed conflict with help rebase, but I'm don't know, rightly that I created additional commit "merge branch 'dev' of ..."

**Comment by Atinux** [comment]
I believe this PR should wait for the removal of babel-preset-env in Nuxt 2.16

**Review by lastthyme — APPROVED** [review]

**Comment by Atinux** [comment]
Hi @shtinmn 

What is the issue with IE11 actually?

**Comment by shtinmn** [comment]
Hi, @Atinux 
Check this https://github.com/nuxt-community/color-mode-module/issues/11#issuecomment-789506373 

There I described my problem in detail

**Comment by Atinux** [comment]
Can you please update your PR (or create another one) to not update the `package.json` and unrelated files to this PR please?

**Pull request closed without merging**
