### PR TITLE
feat: cookie storage

### PR DESCRIPTION
**Pull request by manniL**
PR based on #188 with changes mentioned there.

### CODE REVIEW

**Comment by Atinux** [comment]
Thanks! Happy to check the CI failing?

**Comment by manniL** [comment]
Whoops, yes sure.

**Comment by tasiotas** [comment]
Hi, could you try to run it again to see if CI will pass.
Thank you

**Comment by itpropro** [comment]
Any update on this PR?

**Comment by sharifzadesina** [comment]
It seems older versions of color mode already had cookie storage for SSR support. but newer versions for Nuxt 3, don't.
It will be a good move to support cookie storage again.

**Comment by manniL** [comment]
@atinux Thanks for finishing this up 🔥

**Pull request merged**
